### ISSUE TITLE
Help to reproduce paper results

### ISSUE THREAD

**Issue by gaperezsa** [eth-sri/3dcertify#2]
Hello, I'm trying to reproduce the Z Rotation experiments mentioned in the paper. For the moment, I'm only interested in the Taylor relaxation with Eran verifier (DeepPoly). I followed the instructions in the readme, changed the versions of ELINA and deepg to match with ERAN and got the code running.

However, i have been unable to reproduce the results stated in Table 1 of the paper; specifically, the RotZ values. Which means I want to get  96.7% (87/90) certified accuracy for 20 degrees and 95.7% (86/90) for 60 degree rotations.

I am attaching to this issue some logs created by the the verify_transformation.py program for 1,2,3,4,5,6,20,60,90 degree rotations around the Z axis.
[certification_2021-10-28T18:38:53.log](https://github.com/eth-sri/3dcertify/files/7460074/certification_2021-10-28T18.38.53.log)
[certification_2021-11-01T16:49:06.log](https://github.com/eth-sri/3dcertify/files/7460084/certification_2021-11-01T16.49.06.log)
[certification_2021-11-01T16:49:32.log](https://github.com/eth-sri/3dcertify/files/7460088/certification_2021-11-01T16.49.32.log)
[certification_2021-11-01T16:49:50.log](https://github.com/eth-sri/3dcertify/files/7460092/certification_2021-11-01T16.49.50.log)
[certification_2021-11-01T16:51:53.log](https://github.com/eth-sri/3dcertify/files/7460093/certification_2021-11-01T16.51.53.log)
[certification_2021-11-01T16:54:13.log](https://github.com/eth-sri/3dcertify/files/7460096/certification_2021-11-01T16.54.13.log)
[certification_2021-10-31T14:28:01.log](https://github.com/eth-sri/3dcertify/files/7460097/certification_2021-10-31T14.28.01.log)
[certification_2021-10-31T14:30:22.log](https://github.com/eth-sri/3dcertify/files/7460098/certification_2021-10-31T14.30.22.log)
[certification_2021-10-31T14:28:56.log](https://github.com/eth-sri/3dcertify/files/7460100/certification_2021-10-31T14.28.56.log)

Just with the first logs i could notice that the certified accuracy is decreasing faster than expected, by the 6 degrees certification, the certified accuracy is already at 6/90 (6.67%). For the last 3 logs, 20,60,90 degrees, the program hasn't ended yet, but I'm sending the partial logs. It has been running for two days so far.

This leads me to my second question, I understand that bigger deformations also mean much bigger computation times, however, what is taking so long in my computations is not the linear relaxations but the certification step (this is my first time running interval propagation type certification techniques). In the case of 2 degree certification it takes around 50 seconds per object but in the case of 60 degrees it takes around 50000 seconds per object; are these normal/expected running times for this kind of programs?
`$lscpu`

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
Stepping:            2
CPU MHz:             1424.182
CPU max MHz:         3600.0000
CPU min MHz:         1200.0000
BogoMIPS:            4600.21
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            40960K
NUMA node0 CPU(s):   0-15,32-47
NUMA node1 CPU(s):   16-31,48-63
```

Finally, I noticed that the code explicitly uses CPU and there are no calls what so ever to my GPU, is this normal behavior? or did i miss some installation detail to make use of my GPUs?

**Comment by t-lorenz** [comment]
Hi gaperezsa,
I'm glad you managed to install ERAN with the correct dependencies; unfortunately ERAN often references the "latest" version of dependencies, which makes it difficult to preserve compatibility. This is why our instructions change the install script to checkout a compatible ELINA version before execution (`sed -i'' -e '/^cd ELINA$/a git checkout 2c9a4ea' install.sh`), I will add the same for DeepG (which worked with the latest version until recently).

As to the experiments: according to your logs, you are currently running the experiments with 1 interval only. In this setting, a performance drop is expected due to the increased over-approximation for larger parameter intervals. Table 1 from our paper uses intervals of 2 degrees (page 7: _"All rotations are performed for ±θ, i.e., the total rotation angle is 2θ, with splits of 2° along each dimension."_). To reproduce the result, set the `--intervals` parameter accordingly (e.g., to 20 for +-20 deg rotation).

The runtime of ERAN depends on many parameters, but the trend that it takes significantly longer to certify configurations with lower success rate is consistent with our observations. Except for the max pooling improvements, we mostly treat ERAN as a blackbox certifier.

Regarding GPU support: in theory there is a (partial) GPU implementation of ERAN. However, it was not up to date with the latest changes to ERAN when we ran our experiments, so we decided to run all of them on CPU only. I'm not sure what the current status is. Maybe someone from the ERAN team can help with that.

**Comment by gaperezsa** [comment]
Hello lorenz, 

thank you for explaining the correct use of the intervals parameter, the current running experiments look more promising than before.

also, thank you for the confirmation of the GPU situation, i also intend to to use the ERAN certifier as a blackbox.
